- hosts: db
  tasks:
  - name: Install Apache
    apt:
      name: apache2
      update_cache: yes

  - name: Start httpd
    service:
      name: apache2
      state: started

  - name: Start httpd
    service:
      name: apache2
      enabled: yes

  - name: Install unzip wget
    apt:
      name:
      - unzip 
      - wget
      update_cache: yes