- hosts: db
  tasks:
  - name: Install Apache
    apt:
      name: apache2
      update_cache: yes

  - name: Start httpd
    service:
      name: apache2
      state: started

  - name: Start httpd
    service:
      name: apache2
      enabled: yes

  - name: Install unzip wget
    apt:
      name:
      - unzip 
      - wget
      update_cache: yes

  - name: Download highway.zip
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page258/highway.zip
      dest: /var/www/html